INSERT INTO JIT_USERROLE (ROLEID, DESCRIPTION, CREATEDON) VALUES (JIT_USERROLE_SEQUENCE.NEXTVAL, 'User', SYSDATE);
INSERT INTO JIT_USERROLE (ROLEID, DESCRIPTION, CREATEDON) VALUES (JIT_USERROLE_SEQUENCE.NEXTVAL, 'Admin', SYSDATE);

INSERT INTO JIT_EMPLOYEE (EMPLOYEEID, NAME, EMAIL, PASSWORDHASH, HOURSPERDAY, ROLEID, CREATEDON) VALUES (JIT_EMPLOYEE_SEQUENCE.NEXTVAL, 'Hans Dieter', 'hans.dieter@example.com', '$2a$12$FkMXADzLgozAHRE27/Hhqu5pOR/kCXOS5tvCFXg4JzGf0KjKXHqfq', 8.0, 1, SYSDATE);
INSERT INTO JIT_EMPLOYEE (EMPLOYEEID, NAME, EMAIL, PASSWORDHASH, HOURSPERDAY, ROLEID, CREATEDON) VALUES (JIT_EMPLOYEE_SEQUENCE.NEXTVAL, 'Gustav Peter', 'gustav.peter@example.com', '$2a$12$gTOF/EWOfzQfE7CC71kgye6XBed0/Aj6e3i8eAyV3IlduMWTPxeWu', 6.5, 1, SYSDATE);
INSERT INTO JIT_EMPLOYEE (EMPLOYEEID, NAME, EMAIL, PASSWORDHASH, HOURSPERDAY, ROLEID, CREATEDON) VALUES (JIT_EMPLOYEE_SEQUENCE.NEXTVAL, 'Martin Dieter', 'martin.dieter@example.com', '$2a$12$aX0aCwkgRLM0/hcXF0pZQ.4OpW9l0FFZQeqpEbKWcbQHu9B4qdcdS', 4.5, 1, SYSDATE);
INSERT INTO JIT_EMPLOYEE (EMPLOYEEID, NAME, EMAIL, PASSWORDHASH, HOURSPERDAY, ROLEID, CREATEDON) VALUES (JIT_EMPLOYEE_SEQUENCE.NEXTVAL, 'Steffen Hecht', 'steffen.hecht@example.com', '$2a$12$T9ZHBQB57pdfdxXS22tTauX1RNN0ujl9Emln4BthXsc39dmR7q9BG', 3, 1, SYSDATE);
INSERT INTO JIT_EMPLOYEE (EMPLOYEEID, NAME, EMAIL, PASSWORDHASH, HOURSPERDAY, ROLEID, CREATEDON) VALUES (JIT_EMPLOYEE_SEQUENCE.NEXTVAL, 'Florian Lubitz', 'florian.lubitz@example.com', '$2a$12$LCFqgXg.e5vN73RDMiElT.LCV2c6Wq4k6TBk/W6aMHy42Ag4/puyq', 3, 1, SYSDATE);
INSERT INTO JIT_EMPLOYEE (EMPLOYEEID, NAME, EMAIL, PASSWORDHASH, HOURSPERDAY, ROLEID, CREATEDON) VALUES (JIT_EMPLOYEE_SEQUENCE.NEXTVAL, 'Maximilian Rieger', 'max.rieger@example.com', '$2a$12$kta32o47irOi6UVoX9CdS.1pq0c5DS3.YcNMjis17qyMGfoxYzAw6', 3, 1, SYSDATE);
INSERT INTO JIT_EMPLOYEE (EMPLOYEEID, NAME, EMAIL, PASSWORDHASH, HOURSPERDAY, ROLEID, CREATEDON) VALUES (JIT_EMPLOYEE_SEQUENCE.NEXTVAL, 'Goekhan Erdogan', 'goekhan.erdogan@example.com', '$2a$12$ioIuYjZvoBEmGURC4nuBjeK.b/ibToT9UXbwPWNx4BUCeH/Mv.tRm', 3, 1, SYSDATE);
INSERT INTO JIT_EMPLOYEE (EMPLOYEEID, NAME, EMAIL, PASSWORDHASH, HOURSPERDAY, ROLEID, CREATEDON) VALUES (JIT_EMPLOYEE_SEQUENCE.NEXTVAL, 'Justin Time', 'justin.time@example.com', '$2a$12$sq4c7yt.8VO0OJrHNBJ14.GK27T7TDcrsnm/Y24dSu5hl666IiYmm', 7.0, 1, SYSDATE);

INSERT INTO JIT_CUSTOMER (CUSTOMERID, NAME, STREET, ZIPCODE, CITY, CREATEDON) VALUES (JIT_CUSTOMER_SEQUENCE.NEXTVAL, 'Beispielkunde', 'Beispielstraße 12', '54321', 'Beispielstadt', SYSDATE);
INSERT INTO JIT_CUSTOMER (CUSTOMERID, NAME, STREET, ZIPCODE, CITY, CREATEDON) VALUES (JIT_CUSTOMER_SEQUENCE.NEXTVAL, 'Testkunde', 'Teststraße 42', '12345', 'Teststadt', SYSDATE);
INSERT INTO JIT_CUSTOMER (CUSTOMERID, NAME, STREET, ZIPCODE, CITY, CREATEDON) VALUES (JIT_CUSTOMER_SEQUENCE.NEXTVAL, 'Examplecustomer', 'examplestreet 1', '10001', 'New York', SYSDATE);

INSERT INTO JIT_PROJECT (PROJECTID, NAME, DESCRIPTION, STARTDATE, ENDDATE, ESTIMATEDHOURS, ISFINISHED, CUSTOMERID, CREATEDON) VALUES (JIT_PROJECT_SEQUENCE.NEXTVAL, 'Test', 'Test Project', TO_DATE('24-OKT-2018','DD-MON-YYYY'), TO_DATE('24-OKT-2019','DD-MON-YYYY'), 1000, 0, 1, SYSDATE);
INSERT INTO JIT_PROJECT (PROJECTID, NAME, DESCRIPTION, STARTDATE, ENDDATE, ESTIMATEDHOURS, ISFINISHED, CUSTOMERID, CREATEDON) VALUES (JIT_PROJECT_SEQUENCE.NEXTVAL, 'Beispiel', 'Beispiel Project', TO_DATE('26-OKT-2019','DD-MON-YYYY'), TO_DATE('31-DEZ-2019','DD-MON-YYYY'), 1000, 0, 1, SYSDATE);  

INSERT INTO JIT_MILESTONE (MILESTONEID, NAME, DESCRIPTION, ENDDATE, ESTIMATEDHOURS, PROJECTID, CREATEDON) VALUES (JIT_MILESTONE_SEQUENCE.NEXTVAL, 'Aufgabe 1', 'lorem ipsum dolor sit amet 1.1', TO_DATE('24-NOV-2018','DD-MON-YYYY'), 50, 1, SYSDATE);
INSERT INTO JIT_MILESTONE (MILESTONEID, NAME, DESCRIPTION, ENDDATE, ESTIMATEDHOURS, PROJECTID, CREATEDON) VALUES (JIT_MILESTONE_SEQUENCE.NEXTVAL, 'Aufgabe 2', 'lorem ipsum dolor sit amet 1.2', TO_DATE('27-NOV-2018','DD-MON-YYYY'), 50, 1, SYSDATE);
INSERT INTO JIT_MILESTONE (MILESTONEID, NAME, DESCRIPTION, ENDDATE, ESTIMATEDHOURS, PROJECTID, CREATEDON) VALUES (JIT_MILESTONE_SEQUENCE.NEXTVAL, 'Aufgabe 1', 'lorem ipsum dolor sit amet 2.1', TO_DATE('27-NOV-2018','DD-MON-YYYY'), 50, 2, SYSDATE);

INSERT INTO JIT_PROJECTROLE (ROLEID, DESCRIPTION, CREATEDON) VALUES (JIT_PROJECTROLE_SEQUENCE.NEXTVAL, 'Manager', SYSDATE);
INSERT INTO JIT_PROJECTROLE (ROLEID, DESCRIPTION, CREATEDON) VALUES (JIT_PROJECTROLE_SEQUENCE.NEXTVAL, 'Mitarbeiter', SYSDATE);
  
INSERT INTO JIT_PROJECTMEMBERSHIP (EMPLOYEE_EMPLOYEEID, PROJECT_PROJECTID, CAPACITY, ROLEID, CREATEDON) VALUES (1, 1, 2.5, 1, SYSDATE);
INSERT INTO JIT_PROJECTMEMBERSHIP (EMPLOYEE_EMPLOYEEID, PROJECT_PROJECTID, CAPACITY, ROLEID, CREATEDON) VALUES (2, 1, 1.5, 2, SYSDATE);
INSERT INTO JIT_PROJECTMEMBERSHIP (EMPLOYEE_EMPLOYEEID, PROJECT_PROJECTID, CAPACITY, ROLEID, CREATEDON) VALUES (1, 2, 5.5, 1, SYSDATE);
INSERT INTO JIT_PROJECTMEMBERSHIP (EMPLOYEE_EMPLOYEEID, PROJECT_PROJECTID, CAPACITY, ROLEID, CREATEDON) VALUES (4, 1, 2.5, 1, SYSDATE);
INSERT INTO JIT_PROJECTMEMBERSHIP (EMPLOYEE_EMPLOYEEID, PROJECT_PROJECTID, CAPACITY, ROLEID, CREATEDON) VALUES (4, 2, 2.5, 2, SYSDATE);
INSERT INTO JIT_PROJECTMEMBERSHIP (EMPLOYEE_EMPLOYEEID, PROJECT_PROJECTID, CAPACITY, ROLEID, CREATEDON) VALUES (5, 1, 2.5, 1, SYSDATE);
INSERT INTO JIT_PROJECTMEMBERSHIP (EMPLOYEE_EMPLOYEEID, PROJECT_PROJECTID, CAPACITY, ROLEID, CREATEDON) VALUES (5, 2, 2.5, 2, SYSDATE);
INSERT INTO JIT_PROJECTMEMBERSHIP (EMPLOYEE_EMPLOYEEID, PROJECT_PROJECTID, CAPACITY, ROLEID, CREATEDON) VALUES (6, 1, 2.5, 1, SYSDATE);
INSERT INTO JIT_PROJECTMEMBERSHIP (EMPLOYEE_EMPLOYEEID, PROJECT_PROJECTID, CAPACITY, ROLEID, CREATEDON) VALUES (6, 2, 2.5, 2, SYSDATE);
INSERT INTO JIT_PROJECTMEMBERSHIP (EMPLOYEE_EMPLOYEEID, PROJECT_PROJECTID, CAPACITY, ROLEID, CREATEDON) VALUES (7, 1, 2.5, 1, SYSDATE);
INSERT INTO JIT_PROJECTMEMBERSHIP (EMPLOYEE_EMPLOYEEID, PROJECT_PROJECTID, CAPACITY, ROLEID, CREATEDON) VALUES (7, 2, 2.5, 2, SYSDATE);

INSERT INTO JIT_TIMEBOOKING (BOOKINGID, EMPLOYEEID, MILESTONEID, STARTTIME, ENDTIME, COMMENTS, CREATEDON) VALUES (JIT_TIMEBOOKING_SEQUENCE.NEXTVAL, 1, 1, TO_DATE('01-NOV-2018','DD-MON-YYYY'), TO_DATE('02-NOV-2018','DD-MON-YYYY'), 'Bug gefixt', SYSDATE);
INSERT INTO JIT_TIMEBOOKING (BOOKINGID, EMPLOYEEID, MILESTONEID, STARTTIME, ENDTIME, COMMENTS, CREATEDON) VALUES (JIT_TIMEBOOKING_SEQUENCE.NEXTVAL, 1, 1, TO_DATE('01-NOV-2018','DD-MON-YYYY'), TO_DATE('02-NOV-2018','DD-MON-YYYY'), 'Neues feature getestet', SYSDATE);
INSERT INTO JIT_TIMEBOOKING (BOOKINGID, EMPLOYEEID, MILESTONEID, STARTTIME, ENDTIME, COMMENTS, CREATEDON) VALUES (JIT_TIMEBOOKING_SEQUENCE.NEXTVAL, 2, 1, TO_DATE('01-NOV-2018','DD-MON-YYYY'), TO_DATE('02-NOV-2018','DD-MON-YYYY'), 'Datenbank aufgesetzt', SYSDATE);
INSERT INTO JIT_TIMEBOOKING (BOOKINGID, EMPLOYEEID, MILESTONEID, STARTTIME, ENDTIME, COMMENTS, CREATEDON) VALUES (JIT_TIMEBOOKING_SEQUENCE.NEXTVAL, 2, 1, TO_DATE('01-NOV-2018','DD-MON-YYYY'), TO_DATE('02-NOV-2018','DD-MON-YYYY'), 'Bug gefixt', SYSDATE);
INSERT INTO JIT_TIMEBOOKING (BOOKINGID, EMPLOYEEID, MILESTONEID, STARTTIME, ENDTIME, COMMENTS, CREATEDON) VALUES (JIT_TIMEBOOKING_SEQUENCE.NEXTVAL, 4, 1, TO_DATE('01-NOV-2018','DD-MON-YYYY'), TO_DATE('02-NOV-2018','DD-MON-YYYY'), 'Datenbank aufgesetzt', SYSDATE);
INSERT INTO JIT_TIMEBOOKING (BOOKINGID, EMPLOYEEID, MILESTONEID, STARTTIME, ENDTIME, COMMENTS, CREATEDON) VALUES (JIT_TIMEBOOKING_SEQUENCE.NEXTVAL, 4, 1, TO_DATE('01-DEZ-2018','DD-MON-YYYY'), TO_DATE('02-DEZ-2018','DD-MON-YYYY'), 'Bug gefixt', SYSDATE);
INSERT INTO JIT_TIMEBOOKING (BOOKINGID, EMPLOYEEID, MILESTONEID, STARTTIME, ENDTIME, COMMENTS, CREATEDON) VALUES (JIT_TIMEBOOKING_SEQUENCE.NEXTVAL, 5, 1, TO_DATE('01-NOV-2018','DD-MON-YYYY'), TO_DATE('02-NOV-2018','DD-MON-YYYY'), 'Datenbank aufgesetzt', SYSDATE);
INSERT INTO JIT_TIMEBOOKING (BOOKINGID, EMPLOYEEID, MILESTONEID, STARTTIME, ENDTIME, COMMENTS, CREATEDON) VALUES (JIT_TIMEBOOKING_SEQUENCE.NEXTVAL, 5, 1, TO_DATE('01-DEZ-2018','DD-MON-YYYY'), TO_DATE('02-DEZ-2018','DD-MON-YYYY'), 'Bug gefixt', SYSDATE);
INSERT INTO JIT_TIMEBOOKING (BOOKINGID, EMPLOYEEID, MILESTONEID, STARTTIME, ENDTIME, COMMENTS, CREATEDON) VALUES (JIT_TIMEBOOKING_SEQUENCE.NEXTVAL, 6, 1, TO_DATE('01-NOV-2018','DD-MON-YYYY'), TO_DATE('02-NOV-2018','DD-MON-YYYY'), 'Datenbank aufgesetzt', SYSDATE);
INSERT INTO JIT_TIMEBOOKING (BOOKINGID, EMPLOYEEID, MILESTONEID, STARTTIME, ENDTIME, COMMENTS, CREATEDON) VALUES (JIT_TIMEBOOKING_SEQUENCE.NEXTVAL, 6, 1, TO_DATE('01-DEZ-2018','DD-MON-YYYY'), TO_DATE('02-DEZ-2018','DD-MON-YYYY'), 'Bug gefixt', SYSDATE);
INSERT INTO JIT_TIMEBOOKING (BOOKINGID, EMPLOYEEID, MILESTONEID, STARTTIME, ENDTIME, COMMENTS, CREATEDON) VALUES (JIT_TIMEBOOKING_SEQUENCE.NEXTVAL, 7, 1, TO_DATE('01-NOV-2018','DD-MON-YYYY'), TO_DATE('02-NOV-2018','DD-MON-YYYY'), 'Datenbank aufgesetzt', SYSDATE);
INSERT INTO JIT_TIMEBOOKING (BOOKINGID, EMPLOYEEID, MILESTONEID, STARTTIME, ENDTIME, COMMENTS, CREATEDON) VALUES (JIT_TIMEBOOKING_SEQUENCE.NEXTVAL, 7, 1, TO_DATE('01-DEZ-2018','DD-MON-YYYY'), TO_DATE('02-DEZ-2018','DD-MON-YYYY'), 'Bug gefixt', SYSDATE);
commit;